name: Setup Node and pnpm
description: Sets up Node.js with pnpm, and installs dependencies
inputs:
  node-version:
    description: Node.js version
    required: false
    default: "23"
  pnpm-version:
    description: pnpm version
    required: false
    default: "10"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install vercel cli
      run: pnpm add -g vercel
      shell: bash
