name: Next CI

on:
  push:
    branches:
      - "staging"
      - "feature/**"
      - "main"
    tags:
      - "v*.*.*" # Trigger on semver tags
  pull_request:
    branches:
      - "staging"
  workflow_dispatch: # manual trigger

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check
