name: Next CI

on:
  push:
    branches: ["*"]
    branches-ignore: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["*"]
    branches-ignore: ["main"]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - name: Run lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check
