name: Next CI

on:
  push:
    branches:
      - "staging"
      - "feature/**"
      - "main"
    tags:
      - "v*.*.*" # Trigger on semver tags
  pull_request:
    branches:
      - "staging"
  workflow_dispatch: # manual trigger

jobs:
  lint-and-format:
    if: github.ref != 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check
