name: Next Release CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - run: pnpm lint

      - run: pnpm format:check

  deploy-staging:
    needs: lint-and-format
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - name: Deploy to Vercel (Preview)
        id: vercel-deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          deployment_url=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --skip-domain --yes)
          echo "$deployment_url" > deployment_url.txt
          echo "deployment_url=$deployment_url" >> $GITHUB_OUTPUT

      - name: Upload deployment URL
        uses: actions/upload-artifact@v4
        with:
          name: vercel-deployment-url
          path: deployment_url.txt

      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: "${{ steps.vercel-deploy.outputs.deployment_url }}"
          description: "${{ steps.vercel-deploy.outputs.deployment_url }}"
          environment: Staging

      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ steps.vercel-deploy.outputs.deployment_url }}"
          description: "${{ steps.vercel-deploy.outputs.deployment_url }}"
          environment: Staging
          state: "success"
          deployment_id: "${{ steps.deployment.outputs.deployment_id }}"

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url:
          state: "failure"
          deployment_id: "${{ steps.deployment.outputs.deployment_id }}"
          description: "Failed to deploy"
          environment: Staging

  deploy-production:
    needs: lint-and-format
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - uses: actions/download-artifact@v4
        with:
          name: vercel-deployment-id
          path: .

      - name: Promote to Production
        run: |
          deployment_id=$(cat deployment_id.txt)
          vercel promote "$deployment_id" --token=${{ secrets.VERCEL_TOKEN }} --yes
