name: Next Release CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
env:
  STAGING_URL: "https://dollar-sign-sammce-sammces-projects.vercel.app"
  PRODUCTION_URL: "https://dollar-sign.vercel.app"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - run: pnpm lint

      - run: pnpm format:check

  deploy-staging:
    needs: lint-and-format
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{ env.STAGING_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - name: Deploy to Vercel (Preview)
        id: vercel-deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --skip-domain --yes

  deploy-production:
    needs: lint-and-format
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ env.PRODUCTION_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - name: Promote to Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel promote "$STAGING_URL" --token ${{ secrets.VERCEL_TOKEN }} --scope sammces-projects --yes
